name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "clean-branch" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'teacher-review-app/package-lock.json'

      - name: Install dependencies
        run: cd teacher-review-app && npm ci

      - name: Build
        run: cd teacher-review-app && npm run build
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: teacher-review-app/dist
          branch: gh-pages 